### ISSUE TITLE
Unable to create "Docker Community Edition With Ubuntu 16.04 Lts" VM

### ISSUE THREAD

**Issue by XtremeDR** [MicrosoftLearning/10999-SQL-Server-on-Linux#2]
In Modules 2 and 4 the lab steps ask the user to create a virtual machine with the "Docker Community Edition With Ubuntu 16.04 Lts" image.  This image is not available in any region and cannot be created.  

It is possible to use the Canonical "Ubuntu Server 16.04 LTS" image and install Docker on the VM when using Putty with the following commands:
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add 
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-get install docker-ce
sudo systemctl status docker

Can we ask that the instructions for Modules 2 and 4 be updated to either recommend an image from the Azure Marketplace that is available or to use the image installed in the previous task with Docker installed (with the above commands as a possible example)?

thank you for your consideration

**Comment by AndyFogg** [comment]
Thank you for your comment. I have just checked and the required image is still available. To avoid any confusion, I have updated the search criteria in the Lab docs with the full name of the image - this way the only result returned is the image that is used.
