### ISSUE TITLE
Lab 3: Updated for SQL 2019 IS

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/10999-SQL-Server-on-Linux#3]
Lab instructions to install Integration Services fail at this moment. If you follow the instructions on https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-ssis?view=sql-server-ver15 it will work.

This works:
sudo add-apt-repository "$(curl https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2019.list)"
sudo apt-get update
sudo apt-get install -y mssql-server-is

**Comment by AndyFogg** [comment]
Thank you for you comment and instructions, I have updated the lab accordingly.
